[package]
name = "rustfinity-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
base64 = "0.22.1"
clap = { version = "4.5.11", features = ["derive"] }
duct = "0.13.7"
tokio = { version = "1.39.2", features = ["full"] }
