[package]
name = "challenges"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"
toml = "0.8.12"

[[test]]
name = "tests"
path = "tests.rs"

[[bin]]
name = "cli"
path = "cli.rs"

[lib]
path = "lib.rs"
